version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do echo waiting for db; sleep 2; done;
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
