apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_DB: "{{ .Values.postgres.db }}"
