apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.env.SECRET_KEY }}"
  ALGORITHM: "{{ .Values.env.ALGORITHM }}"
  ACCESS_TOKEN_EXPIRE_MINUTES: "{{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
