image:
  repository: kajalks/task-manager-app
  tag: 2a121dc9aa8ad3baba8a6f87c08b7f9ae43a147d

env:
  SECRET_KEY: ""
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"

postgres:
  user: postgres
  password: root
  db: taskdb
  port: 5432
