image:
  repository: kajalks/task-manager-app
  tag: 9ea4c593666dbc8dbf5e3c2ef5504dfd43c2341a

env:
  SECRET_KEY: ""
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"

postgres:
  user: postgres
  password: root
  db: taskdb
  port: 5432
