image:
  repository: kajalks/task-manager-app
  tag: 8544d9e28653b7d6a4dced01f21de90150d6d97a

env:
  SECRET_KEY: ""
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"

postgres:
  user: postgres
  password: root
  db: taskdb
  port: 5432
