name: CI - FastAPI Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kajalks/task-manager-app:latest .

      - name: Show Docker images
        run: docker images
  
      - name: Push Docker image
        run: docker push kajalks/task-manager-app:latest

      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install task-manager-app ./helm \
            --set image.repository="kajalks/task-manager-app" \
            --set image.tag="latest" \
            --set env.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --set env.ALGORITHM="${{ secrets.ALGORITHM }}" \
            --set env.ACCESS_TOKEN_EXPIRE_MINUTES="${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" \
            --set postgres.user="${{ secrets.POSTGRES_USER }}" \
            --set postgres.password="${{ secrets.POSTGRES_PASSWORD }}" \
            --set postgres.db="${{ secrets.POSTGRES_DB }}"
