name: CI - FastAPI Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t kajalks/task-manager-app:${{ env.IMAGE_TAG }} .

      - name: Show Docker images
        run: docker images
  
      - name: Push Docker image
        run: docker push kajalks/task-manager-app:${{ env.IMAGE_TAG }}
      
      # Update Helm values.yaml
      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag:.*|tag: ${{ env.IMAGE_TAG }}|" helm/values.yaml

      # Commit Helm change
      - name: Commit Helm update
        run: |
          git config user.name "KajalSund"
          git config user.email "kajal.sund9@gmail.com"
          git add helm/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
      